apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: people-service
  name: people-service
spec:
  ports:
    - name: 18089-tcp
      port: 18089
      targetPort: 18089
  selector:
    io.kompose.service: people-service
