apiVersion: v1
kind: Service
metadata:
  labels:
    app: reference-data
  name: reference-data
spec:
  ports:
    - name: "18085"
      port: 8080
      targetPort: 18085
  selector:
    app: reference-data
