apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: trade-feed-claim0
  name: trade-feed-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
