apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: trade-service
  name: trade-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trade-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/traderx-localnet: "true"
        io.kompose.service: trade-service
    spec:
      containers:
        - args:
            - ./gradlew
            - bootRun
          env:
            - name: ACCOUNT_SERVICE_HOST
              value: account-service
            - name: DATABASE_TCP_HOST
              value: database
            - name: PEOPLE_SERVICE_HOST
              value: people-service
            - name: REFERENCE_DATA_HOST
              value: reference-data
            - name: TRADE_FEED_HOST
              value: trade-feed
          image: traderx.azurecr.io/trade-service
          name: trade-service
          ports:
            - containerPort: 18092
              hostPort: 18092
              protocol: TCP
          volumeMounts:
            - mountPath: /workspace
              name: trade-service-claim0
          workingDir: /trade-service
      restartPolicy: Always
      volumes:
        - name: trade-service-claim0
          persistentVolumeClaim:
            claimName: trade-service-claim0
