apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: trade-processor
  name: trade-processor
spec:
  ports:
    - name: 18091-tcp
      port: 18091
      targetPort: 18091
  selector:
    io.kompose.service: trade-processor
