apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: account-service
  name: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: account-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/traderx-localnet: "true"
        io.kompose.service: account-service
    spec:
      containers:
        - args:
            - ./gradlew
            - bootRun
          env:
            - name: DATABASE_TCP_HOST
              value: database
            - name: PEOPLE_SERVICE_HOST
              value: people-service
            - name: ACCOUNT_SERVICE_PORT
              value: "18088"
          image: traderx.azurecr.io/account-service
          name: account-service
          ports:
            - containerPort: 18088
              hostPort: 18088
              protocol: TCP
          volumeMounts:
            - mountPath: /workspace
              name: account-service-claim0
          workingDir: /account-service
      restartPolicy: Always
      volumes:
        - name: account-service-claim0
          persistentVolumeClaim:
            claimName: account-service-claim0
