apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: reference-data
  name: reference-data
spec:
  ports:
    - name: 18085-tcp
      port: 18085
      targetPort: 18085
  selector:
    io.kompose.service: reference-data
