name: License Scanning for Node.js

on:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:
    paths:
      - '**/package-json.lock'
      - '**/package.json'
      - '.github/workflows/license-scanning-node.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']
        module-folder: [
          'reference-data',
          'trade-feed',
          'web-front-end/angular',
          'web-front-end/react'
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install --omit=dev
#       - run: yarn install --production --frozen-lockfile
        working-directory: ${{ matrix.module-folder }}
      - run: npm install -g node-license-validator
        working-directory: ${{ matrix.module-folder }}
      - run: node-license-validator . --allow-licenses Apache-2.0 MIT BSD-2-Clause BSD BSD-3-Clause Unlicense ISC
        working-directory: ${{ matrix.module-folder }}
